// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskNinja.Services;

#nullable disable

namespace TaskNinja.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TaskNinja.Models.TodoTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2023, 12, 20, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(112),
                            Description = "Dummy task description 1",
                            DueDate = new DateTime(2024, 1, 4, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(167),
                            Name = "Task 1",
                            Priority = "Low",
                            Status = "NotStarted"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2023, 12, 22, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(176),
                            Description = "Dummy task description 2",
                            DueDate = new DateTime(2024, 1, 2, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(179),
                            Name = "Task 2",
                            Priority = "Medium",
                            Status = "InProgress"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2023, 12, 23, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(183),
                            Description = "Dummy task description 3",
                            DueDate = new DateTime(2023, 12, 24, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(185),
                            Name = "Task 3",
                            Priority = "High",
                            Status = "NotStarted"
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2023, 12, 18, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(188),
                            Description = "Dummy task description 4",
                            DueDate = new DateTime(2024, 1, 6, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(191),
                            Name = "Task 4",
                            Priority = "Medium",
                            Status = "Completed"
                        },
                        new
                        {
                            ID = 5,
                            CreatedDate = new DateTime(2023, 12, 24, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(194),
                            Description = "Dummy task description 5",
                            DueDate = new DateTime(2023, 12, 30, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(196),
                            Name = "Task 5",
                            Priority = "Low",
                            Status = "NotStarted"
                        },
                        new
                        {
                            ID = 6,
                            CreatedDate = new DateTime(2023, 12, 21, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(201),
                            Description = "Dummy task description 6",
                            DueDate = new DateTime(2024, 1, 1, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(204),
                            Name = "Task 6",
                            Priority = "High",
                            Status = "InProgress"
                        },
                        new
                        {
                            ID = 7,
                            CreatedDate = new DateTime(2023, 12, 19, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(207),
                            Description = "Dummy task description 7",
                            DueDate = new DateTime(2024, 1, 14, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(210),
                            Name = "Task 7",
                            Priority = "Medium",
                            Status = "NotStarted"
                        },
                        new
                        {
                            ID = 8,
                            CreatedDate = new DateTime(2023, 12, 23, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(213),
                            Description = "Dummy task description 8",
                            DueDate = new DateTime(2024, 1, 3, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(215),
                            Name = "Task 8",
                            Priority = "Low",
                            Status = "InProgress"
                        },
                        new
                        {
                            ID = 9,
                            CreatedDate = new DateTime(2023, 12, 17, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(218),
                            Description = "Dummy task description 9",
                            DueDate = new DateTime(2024, 1, 8, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(221),
                            Name = "Task 9",
                            Priority = "High",
                            Status = "Completed"
                        },
                        new
                        {
                            ID = 10,
                            CreatedDate = new DateTime(2023, 12, 24, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(226),
                            Description = "Dummy task description 10",
                            DueDate = new DateTime(2023, 12, 30, 13, 14, 27, 690, DateTimeKind.Local).AddTicks(228),
                            Name = "Task 10",
                            Priority = "High",
                            Status = "NotStarted"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
